### PR TITLE
2 authentication login

### PR DESCRIPTION
**Pull request by caudaganesh**
#2 #1 
register code from #1 

breakdown :

- [x] login with username password
- [x] login with phone
- [x] redirect on unregistered

### CODE REVIEW

**Comment by caudaganesh** [comment]
screenshot_2017-09-26-16-39-11-711_io devsummit devsummit
screenshot_2017-09-26-16-39-21-072_io devsummit devsummit
screenshot_2017-09-26-16-39-37-665_io devsummit devsummit
screenshot_2017-09-26-16-40-07-864_com google android gms
screenshot_2017-09-26-16-40-28-972_io devsummit devsummit
screenshot_2017-09-26-16-40-39-009_io devsummit devsummit
screenshot_2017-09-26-16-45-55-218_io devsummit devsummit
screenshot_2017-09-26-16-46-15-401_io devsummit devsummit

**Review by mgufrone — APPROVED** [review]
This looks nice

**Comment by mgufrone** [comment]
@caudaganesh so are you saying that this PR covered 2 issues at once? Because I don't see @wlisrausr commit here

**Comment by wndisra** [comment]
There are some activities (java) and styles (xml) from my branch here. @caudaganesh merged it to his branch to use some styling. That's why he mentioned my issue too. I'll make another PR related to register functionality today @mgufrone

**Pull request merged**
